### ISSUE TITLE
Make `echo_request_headers` function public

### ISSUE THREAD

**Issue by thiagomajesk** [webstronauts/ex_unpoly#1]
Hi! I'd like the ability to instruct Unpoly to update the browser history after a POST request. This is particularly useful in cases where you have dependent resources with shared templates, for example:

1- [GET] `/post/how-to-work-with-unpoly` (Renders post with comments)
2- [POST] `/post_comment` (User submitting a new comment)
3- Then, redirects back to the post "show" URL. Since the common pattern in Phoenix is to re-render the template if the changeset is invalid, the browser history would get stuck in `/post_comment`.

For this, to work we should make  `echo_request_headers/1` public and also create a `echo_request_headers/2` with an optional argument for the user to pass the desired URL (if not the current one)

**Comment by robinvdvleuten** [comment]
It doesn't feel right to make the function public for this particular use case. What I could do though, is adding two additional helper methods where you can set the response headers on the connection;

```ex
# ...

def put_resp_location_header(conn, value) do
  Plug.Conn.put_resp_header("x-up-location", value)
end

def put_resp_method_header(conn, value) do
  Plug.Conn.put_resp_header("x-up-method", value)
end

defp echo_request_headers(conn) do
  conn
  |> put_resp_location_header(Phoenix.Controller.current_url(conn))
  |> put_resp_method_header(conn.method)
end

# ...
```  

Would something like that work for you?

**Comment by robinvdvleuten** [comment]
See commit e56a3ee4a66a9e111cc6619e980de43a0a105e48

**Comment by thiagomajesk** [comment]
@robinvdvleuten Thanks for the reply I'm glad you got the general idea 😄.
