### ISSUE TITLE
Support for the Unpoly 2 protocol

### ISSUE THREAD

**Issue by triskweline** [webstronauts/ex_unpoly#4]
Thank you for maintaining this package!

This is just a heads up that [Unpoly 2](https://v2.unpoly.com) is going to be released this week. 

Unpoly 2 comes with several extensions to the [optional server protocol](https://v2.unpoly.com/up.protocol) that this repo implements. **All protocol changes are backwards compatible**, so Unpoly 2 users can keep using this package.

You may want to consider whether you want to implement some of the newer features like [`X-Up-Events`](https://v2.unpoly.com/X-Up-Events), [`X-Up-Mode`](https://v2.unpoly.com/X-Up-Mode) or [`X-Up-Accept-Layer`](https://v2.unpoly.com/X-Up-Accept-Layer).

If you're planning to stick with the current feature set, that's cool too, of course.

**Comment by robinvdvleuten** [comment]
@triskweline thanks for reaching out and good work with the v2! Do you have a changelog of all new Unpoly features or is it only the four you mentioned here?

**Comment by triskweline** [comment]
It's more than these four.

From what I could see in the code, `ex_unpoly` currently supports the following:

- `X-Up-Target` (Request header)
- `X-Up-Validate` (Request header)
- `X-Up-Location` (Response header)
- `X-Up-Method` (Response header)
- `X-Up-Title` (Response header)
- `_up_cookie` (Cookie)

Changes in V2 are:

- All entries in <https://v2.unpoly.com/up.protocol> not mentioned above
- The server may also send a `X-Up-Target` *response* header to change the render target
- The user can configure to not send an `X-Up-Target` request header to improve cacheability on the client. To reliably detect an Unpoly request in V2 (`Unpoly.unpoly?`) you should test for presence of the `X-Up-Version` header, which is always guaranteed to be sent.

**Comment by robinvdvleuten** [comment]
I also see that some response headers also can be set to `null`. Is this a JSON encoded null, like `"null"`?

**Comment by triskweline** [comment]
It is the string `null` (no quotes), e.g. `X-Up-Accept-Layer: null`.
